# Alt küme üzerinde işlem yapmak

In [2]:
import numpy as np

In [3]:
a = np.random.randint(10, size=(5,5))
a

array([[7, 8, 3, 7, 8],
       [4, 9, 3, 5, 5],
       [0, 9, 9, 7, 1],
       [6, 9, 5, 3, 3],
       [0, 2, 7, 0, 6]])

In [4]:
alt_a = a[0:3, 0:2]
alt_a

array([[7, 8],
       [4, 9],
       [0, 9]])

In [5]:
alt_a[0,0] = 9999
alt_a[1,1] = 888
alt_a

array([[9999,    8],
       [   4,  888],
       [   0,    9]])

In [6]:
#Görüldüğü üzere alt kümede yapılan değişiklikler ana kümeyide etkiler 
a

array([[9999,    8,    3,    7,    8],
       [   4,  888,    3,    5,    5],
       [   0,    9,    9,    7,    1],
       [   6,    9,    5,    3,    3],
       [   0,    2,    7,    0,    6]])

## Copy kullanarak kullanım etkiden kurtulma

In [8]:
m = np.random.randint(10, size=(5,5))
m

array([[6, 3, 5, 6, 1],
       [0, 4, 8, 3, 1],
       [6, 6, 1, 3, 8],
       [6, 1, 5, 5, 7],
       [3, 5, 7, 4, 6]])

In [9]:
# copy metodu sona eklenirse etkilerden kurtulunur(Ana arrayden bağımsız olur)
alt_m = m[0:3, 0:2].copy()
alt_m

array([[6, 3],
       [0, 4],
       [6, 6]])

In [10]:
alt_m[0][0] = 4444
alt_m[1][1] = 111
alt_m

array([[4444,    3],
       [   0,  111],
       [   6,    6]])

In [11]:
m

array([[6, 3, 5, 6, 1],
       [0, 4, 8, 3, 1],
       [6, 6, 1, 3, 8],
       [6, 1, 5, 5, 7],
       [3, 5, 7, 4, 6]])