# Fancy Index ile elemanlara erişmek

In [2]:
import numpy as np

In [3]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [4]:
v[1]

3

In [5]:
v[3]

9

In [6]:
v[5]

15

In [7]:
# Yan yana gösterme bu şekilde yapılır
[v[1], v[3], v[5]]

[3, 9, 15]

In [8]:
# bu şekilde kullanıma fancy index denir
al_getir = [1,3,5]

In [9]:
v[al_getir]

array([ 3,  9, 15])

## İki boyutta fancy index

In [11]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
#satir = np.array([0,1]) # bu şekilde de yapılabilir
satir = [0,1]
sütun = [1,2]
m[satir, sütun]

array([1, 5])

In [13]:
# Basit index ile fancy index

In [14]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
m[0, [1,2]]

array([1, 2])

In [16]:
# Slice ile fancy

In [17]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])