# Koşullu Eleman İşlemleri

In [2]:
import numpy as np

In [3]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [4]:
v < 3

array([ True,  True, False, False, False])

In [5]:
# Bu koşulu sağlayan elemanları döner 
v[v<3]

array([1, 2])

In [6]:
v[v != 3] 

array([1, 2, 4, 5])

In [7]:
v

array([1, 2, 3, 4, 5])

In [8]:
v * 2

array([ 2,  4,  6,  8, 10])