# Matematiksel İşlemler

In [2]:
import numpy as np

In [3]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [4]:
v - 1

array([0, 1, 2, 3, 4])

In [5]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [6]:
# ufunc arka planda aslında bu fonksiyonlar çalıştırılır. Yukarıdaki operatör kullanımı aşağıdakileri çalıştırır 

In [7]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [8]:
np.multiply(v, 4)

array([ 4,  8, 12, 16, 20])

In [9]:
# v % 2
np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [10]:
# Mutlak değer
np.absolute(np.array([-2, 5, -1]))

array([2, 5, 1])

In [11]:
np.sin(360)

0.9589157234143065

In [12]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [13]:
np.log2(v)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [14]:
v

array([1, 2, 3, 4, 5])

In [15]:
np.mean(v)

3.0

In [16]:
np.median(v)

3.0

In [17]:
v.mean()

3.0

In [18]:
np.sum(v)

15

## Numpy ile iki bilinmeyenli denklem çözümü

5 * x0 + x1 = 12

x0 + 3 * x1 = 10

In [21]:
a = np.array([[5, 1], [1, 3]])
b = np.array([12, 10])

In [22]:
a

array([[5, 1],
       [1, 3]])

In [23]:
b

array([12, 10])

In [24]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])