# Numpy Array'i Oluşturmak

In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
a = np.array([1,2,3,4,5])

In [5]:
type(a)

numpy.ndarray

In [6]:
np.array([3.14, 2, 3, 4, 9], dtype = "int")

array([3, 2, 3, 4, 9])

## Sıfırdan Array Oluşturma

In [8]:
np.zeros(10, dtype = 'int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.ones((3,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [11]:
#Doğrusal array oluşturma
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [12]:
# 0 ile 1 arasında tek boyutlu 10 tane sayı oluşturma
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [13]:
np.linspace(0, 100, 10, dtype="int")

array([  0,  11,  22,  33,  44,  55,  66,  77,  88, 100])

In [14]:
# Rastgele sayılardan oluşacak fakat dağılımını kendimizin belirlediği bir
# matris bu şekilde yapılır ortalaması 10 standart sapması 4, kaça kaçlık
np.random.normal(10, 4, (3,4))

array([[17.8764284 , 11.32852508, 13.55167107,  9.08747849],
       [ 1.56868336,  8.16192985, 10.4683895 , 10.8539227 ],
       [ 7.77709791,  5.56041304, 11.03028758, 16.05601541]])

In [15]:
# Rastgele integer değerlerden matris üretme
np.random.randint(0, 10, (3,3))

array([[8, 0, 1],
       [1, 3, 5],
       [0, 5, 6]])