# Numpy Array Özellikleri

* **ndim**: _boyut sayısı_
* **shape**: boyut bilgisi
* **size**: toplam eleman sayısı
* **dtype**: array veri tipi

In [3]:
import numpy as np

In [4]:
np.random.randint(10, size=10)

array([5, 8, 8, 3, 4, 0, 6, 0, 1, 5])

In [5]:
a = np.random.randint(10, size=10)
a

array([3, 6, 4, 6, 7, 5, 5, 2, 7, 3])

In [6]:
a.ndim

1

In [7]:
a.shape

(10,)

In [8]:
a.size

10

In [9]:
a.dtype

dtype('int32')

In [10]:
#np.random.randint(0, 10, (3,5))
b = np.random.randint(10, size = (3,5))
b

array([[6, 9, 8, 1, 3],
       [4, 9, 7, 7, 5],
       [5, 6, 9, 3, 3]])

In [11]:
b.ndim

2

In [12]:
b.shape

(3, 5)

In [13]:
b.size

15

In [14]:
b.dtype

dtype('int32')