# Array Sıralama (Sorting)

In [2]:
import numpy as np

In [3]:
v = np.array([7, 3, 1, 11, 20, 2, 5, 0])
v

array([ 7,  3,  1, 11, 20,  2,  5,  0])

In [4]:
# numpy içinden çağırılan sort metodu orjinali bozmaz yeniden atama yapılmadığı sürece
np.sort(v)

array([ 0,  1,  2,  3,  5,  7, 11, 20])

In [5]:
v

array([ 7,  3,  1, 11, 20,  2,  5,  0])

In [6]:
# numpy içinden olmayan sort metodu ise yapıyı tamamen bozar
v.sort()

In [7]:
v

array([ 0,  1,  2,  3,  5,  7, 11, 20])

## İki Boyutlu Sıralama

In [9]:
m = np.random.normal(20, 5, (3,3))
m

array([[19.05289715, 17.99793884, 17.50903053],
       [18.34818839, 21.17769152, 12.88484069],
       [23.38998563, 15.02980821, 13.79482539]])

In [10]:
# Satıra göre sıralama yapar axis = 1
np.sort(m, axis=1)

array([[17.50903053, 17.99793884, 19.05289715],
       [12.88484069, 18.34818839, 21.17769152],
       [13.79482539, 15.02980821, 23.38998563]])

In [11]:
# Sütuna göre sıralama yapar axis = 0
np.sort(m, axis=0)

array([[18.34818839, 15.02980821, 12.88484069],
       [19.05289715, 17.99793884, 13.79482539],
       [23.38998563, 21.17769152, 17.50903053]])