# Index ile elemanlara erişmek

In [2]:
import numpy as np

In [3]:
a = np.random.randint(10, size = 10)
a

array([5, 3, 7, 1, 3, 0, 8, 9, 5, 3])

In [4]:
a[0]

5

In [5]:
a[-1]

3

In [6]:
a[0] = 100
a

array([100,   3,   7,   1,   3,   0,   8,   9,   5,   3])

In [7]:
m = np.random.randint(10, size = (3,5))
m

array([[4, 9, 7, 6, 0],
       [7, 6, 2, 3, 8],
       [2, 1, 8, 7, 9]])

In [8]:
m[0][0]

4

In [9]:
m[1][1]

6

In [10]:
m[1][1] = 2
m[1][1]

2