# Slicing(Kesme) ile elemanlara erişmek(Array alt kümesine erişmek)

In [2]:
import numpy as np

In [3]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
a[0:3]

array([20, 21, 22])

In [5]:
a[:3]

array([20, 21, 22])

In [6]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [7]:
a[1::2]

array([21, 23, 25, 27, 29])

## İki boyutlu slicing işlemleri

In [9]:
m = np.random.randint(10, size= (5,5))
m

array([[5, 6, 6, 6, 8],
       [5, 1, 9, 4, 2],
       [4, 5, 2, 7, 8],
       [8, 3, 3, 8, 2],
       [9, 3, 5, 3, 9]])

In [10]:
# ilk kısım satırları(row) temsil eder. Hiçbir şey girilmezse bütün satırları al demektir
# ikinci kısım sütunları(column) temsil eder.
m[:,0]

array([5, 5, 4, 8, 9])

In [11]:
m[:,1]

array([6, 1, 5, 3, 3])

In [12]:
m

array([[5, 6, 6, 6, 8],
       [5, 1, 9, 4, 2],
       [4, 5, 2, 7, 8],
       [8, 3, 3, 8, 2],
       [9, 3, 5, 3, 9]])

In [13]:
m[0,:]

array([5, 6, 6, 6, 8])

In [14]:
m[:3,:2]

array([[5, 6],
       [5, 1],
       [4, 5]])

In [15]:
m[0:2, 0:3]

array([[5, 6, 6],
       [5, 1, 9]])